//Orders
export const SET_ORDER_SUCCESS = 'SET_ORDER_SUCCESS';
export const SET_ORDER_FAILURE = 'SET_ORDER_FAILURE';

export const SET_ORDER_STATUS_SUCCESS = 'SET_ORDER_STATUS_SUCCESS';
export const SET_ORDER_STATUS_FAILURE = 'SET_ORDER_STATUS_FAILURE';

export const UPDATE_ORDER_STATUS_SUCCESS = 'UPDATE_ORDER_STATUS_SUCCESS';
export const UPDATE_ORDER_STATUS_FAILURE = 'UPDATE_ORDER_STATUS_FAILURE';

//NOTIFICATIONS
export const DELETE_NOTIFICATION_SUCCESS = 'DELETE_NOTIFICATION_SUCCESS';
export const NEW_NOTIFICATION_SUCCESS = 'NEW_NOTIFICATION_SUCCESS';

//PAGES
export const SET_PAGE_INFO_SUCCESS = 'SET_PAGE_INFO_SUCCESS';