//Orders
export const SET_ORDER_SUCCESS = 'SET_ORDER_SUCCESS';
export const SET_ORDER_FAILURE = 'SET_ORDER_FAILURE';

export const SET_ORDER_STATUS_SUCCESS = 'SET_ORDER_STATUS_SUCCESS';
export const SET_ORDER_STATUS_FAILURE = 'SET_ORDER_STATUS_FAILURE';

export const UPDATE_ORDER_STATUS_SUCCESS = 'UPDATE_ORDER_STATUS_SUCCESS';
export const UPDATE_ORDER_STATUS_FAILURE = 'UPDATE_ORDER_STATUS_FAILURE';


//WebSocket
export const CONNECT_SOCKET_SUCCESS = 'CONNECT_SOCKET_SUCCESS';
export const CONNECT_SOCKET_FAILURE = 'CONNECT_SOCKET_FAILURE';

export const CONNECT_TOPIC_SUCCESS = 'CONNECT_TOPIC_SUCCESS';
export const CONNECT_TOPIC_FAILURE = 'CONNECT_TOPIC_FAILURE';

export const SOCKET_SUBSCRIBE_SUCCESS = 'SOCKET_SUBSCRIBE_SUCCESS';
export const SOCKET_SUBSCRIBE_FAILURE = 'SOCKET_SUBSCRIBE_FAILURE';

//NOTIFICATIONS
export const DELETE_NOTIFICATION_SUCCESS = 'DELETE_NOTIFICATION_SUCCESS';
export const NEW_NOTIFICATION_SUCCESS = 'NEW_NOTIFICATION_SUCCESS';